# Generated by Django 4.1 on 2022-08-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=32)),
                ('Armament', models.CharField(max_length=255)),
                ('Equipment', models.CharField(max_length=255)),
                ('Feature', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Battleship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=32)),
                ('Armament', models.CharField(max_length=255)),
                ('Equipment', models.CharField(max_length=255)),
                ('Feature', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=32)),
                ('Armament', models.CharField(max_length=255)),
                ('Equipment', models.CharField(max_length=255)),
                ('Expertise', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Helicopter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=32)),
                ('Armament', models.CharField(max_length=255)),
                ('Equipment', models.CharField(max_length=255)),
                ('Feature', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=32)),
                ('Armament', models.CharField(max_length=255)),
                ('Equipment', models.CharField(max_length=255)),
                ('Feature', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
