# Generated by Django 4.1 on 2022-08-17 04:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=32)),
                ('armament', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64), default=list, size=None)),
                ('equipment', models.CharField(max_length=255)),
                ('feature', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Battleship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=32)),
                ('armament', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64), default=list, size=None)),
                ('equipment', models.CharField(max_length=255)),
                ('feature', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=32)),
                ('armament', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64), default=list, size=None)),
                ('equipment', models.CharField(max_length=255)),
                ('expertise', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Helicopter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=32)),
                ('armament', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64), default=list, size=None)),
                ('equipment', models.CharField(max_length=255)),
                ('feature', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=32)),
                ('armament', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64), default=list, size=None)),
                ('equipment', models.CharField(max_length=255)),
                ('feature', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
