# Generated by Django 4.1 on 2022-08-17 05:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarThunder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='equipment',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='battleship',
            name='equipment',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='crew',
            name='equipment',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='helicopter',
            name='equipment',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='tank',
            name='equipment',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64), default=list, size=None),
        ),
    ]
