# Generated by Django 4.1 on 2022-08-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarThunder', '0003_alter_aircraft_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='battleship',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='crew',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='helicopter',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tank',
            name='description',
            field=models.TextField(),
        ),
    ]
