# Generated by Django 4.1 on 2022-08-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarThunder', '0004_alter_aircraft_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='battleship',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='crew',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='helicopter',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tank',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
