# Generated by Django 4.1 on 2022-08-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarThunder', '0005_alter_aircraft_id_alter_battleship_id_alter_crew_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='feature',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='feature',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='battleship',
            name='feature',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='helicopter',
            name='feature',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tank',
            name='feature',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
